import baseQuery from "./baseQuery"
import type {
  AdminSchoolTeacher,
  AdminSchoolTeacherUser,
  AuthFactor,
  Class,
  IndependentUser,
  NonAdminSchoolTeacher,
  NonAdminSchoolTeacherUser,
  NonSchoolTeacher,
  NonSchoolTeacherUser,
  OtpBypassToken,
  School,
  SchoolTeacher,
  SchoolTeacherUser,
  Student,
  StudentUser,
  Teacher,
  TeacherUser,
  User,
} from "./models"
import tagTypes from "./tagTypes"
import urls from "./urls"

export {
  baseQuery,
  tagTypes,
  urls,
  type AdminSchoolTeacher,
  type AdminSchoolTeacherUser,
  type AuthFactor,
  type Class,
  type IndependentUser,
  type NonAdminSchoolTeacher,
  type NonAdminSchoolTeacherUser,
  type NonSchoolTeacher,
  type NonSchoolTeacherUser,
  type OtpBypassToken,
  type School,
  type SchoolTeacher,
  type SchoolTeacherUser,
  type Student,
  type StudentUser,
  type Teacher,
  type TeacherUser,
  type User,
}
