export type Required<T, K extends keyof T> = { [P in K]-?: T[P] }
export type Optional<T, K extends keyof T> = Partial<Pick<T, K>>
export type OptionalPropertyNames<T> = {
  [K in keyof T]-?: {} extends { [P in K]: T[K] } ? K : never
}[keyof T]
export type IsOptional<T, K extends keyof T> =
  K extends OptionalPropertyNames<T> ? true : false

export function openInNewTab(url: string, target = "_blank"): void {
  window.open(url, target)
}

export function wrap(
  newFn: {
    before?: (...args: any[]) => void
    after?: (...args: any[]) => void
  },
  fn?: (...args: any[]) => any,
): (...args: any[]) => any {
  return (...args) => {
    if (newFn.before !== undefined) {
      newFn.before(...(args as unknown[]))
    }
    let value
    if (fn !== undefined) {
      value = fn(...(args as unknown[])) as unknown
    }
    if (newFn.after !== undefined) {
      newFn.after(...(args as unknown[]))
    }
    return value
  }
}

export function snakeCaseToCamelCase(obj: Record<string, any>): void {
  Object.entries(obj).forEach(([snakeKey, value]) => {
    if (typeof value === "object") snakeCaseToCamelCase(value as object)

    const camelKey = snakeKey.replace(/_+[a-z]/g, _char =>
      _char[_char.length - 1].toUpperCase(),
    )

    delete obj[snakeKey]
    obj[camelKey] = value as unknown
  })
}

export function camelCaseToSnakeCase(obj: Record<string, any>): void {
  Object.entries(obj).forEach(([camelKey, value]) => {
    if (typeof value === "object") camelCaseToSnakeCase(value as object)

    const snakeKey = camelKey.replace(
      /[A-Z]/g,
      char => `_${char.toLowerCase()}`,
    )

    delete obj[camelKey]
    obj[snakeKey] = value as unknown
  })
}

export const MIN_DATE = new Date(0, 0, 0)

export const COUNTRY_ISO_CODES = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BV",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HM",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TF",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "UM",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
] as const

export type CountryIsoCodes = (typeof COUNTRY_ISO_CODES)[number]

export const COUNTRIES = [
  "Andorra",
  "United Arab Emirates (the)",
  "Afghanistan",
  "Antigua and Barbuda",
  "Anguilla",
  "Albania",
  "Armenia",
  "Angola",
  "Antarctica",
  "Argentina",
  "American Samoa",
  "Austria",
  "Australia",
  "Aruba",
  "Åland Islands",
  "Azerbaijan",
  "Bosnia and Herzegovina",
  "Barbados",
  "Bangladesh",
  "Belgium",
  "Burkina Faso",
  "Bulgaria",
  "Bahrain",
  "Burundi",
  "Benin",
  "Saint Barthélemy",
  "Bermuda",
  "Brunei Darussalam",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Brazil",
  "Bahamas (the)",
  "Bhutan",
  "Bouvet Island",
  "Botswana",
  "Belarus",
  "Belize",
  "Canada",
  "Cocos (Keeling) Islands (the)",
  "Congo (the Democratic Republic of the)",
  "Central African Republic (the)",
  "Congo (the)",
  "Switzerland",
  "Côte d'Ivoire",
  "Cook Islands (the)",
  "Chile",
  "Cameroon",
  "China",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Cabo Verde",
  "Curaçao",
  "Christmas Island",
  "Cyprus",
  "Czechia",
  "Germany",
  "Djibouti",
  "Denmark",
  "Dominica",
  "Dominican Republic (the",
  "Algeria",
  "Ecuador",
  "Estonia",
  "Egypt",
  "Western Sahara",
  "Eritrea",
  "Spain",
  "Ethiopia",
  "Finland",
  "Fiji",
  "Falkland Islands (the) [Malvinas]",
  "Micronesia (Federated States of)",
  "Faroe Islands (the)",
  "France",
  "Gabon",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "Grenada",
  "Georgia",
  "French Guiana",
  "Guernsey",
  "Ghana",
  "Gibraltar",
  "Greenland",
  "Gambia (the)",
  "Guinea",
  "Guadeloupe",
  "Equatorial Guinea",
  "Greece",
  "South Georgia and the South Sandwich Islands",
  "Guatemala",
  "Guam",
  "Guinea-Bissau",
  "Guyana",
  "Hong Kong",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Croatia",
  "Haiti",
  "Hungary",
  "Indonesia",
  "Ireland",
  "Israel",
  "Isle of Man",
  "India",
  "British Indian Ocean Territory (the)",
  "Iraq",
  "Iran (Islamic Republic of)",
  "Iceland",
  "Italy",
  "Jersey",
  "Jamaica",
  "Jordan",
  "Japan",
  "Kenya",
  "Kyrgyzstan",
  "Cambodia",
  "Kiribati",
  "Comoros (the)",
  "Saint Kitts and Nevis",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Cayman Islands (the)",
  "Kazakhstan",
  "Lao People's Democratic Republic (the)",
  "Lebanon",
  "Saint Lucia",
  "Liechtenstein",
  "Sri Lanka",
  "Liberia",
  "Lesotho",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Libya",
  "Morocco",
  "Monaco",
  "Moldova (the Republic of)",
  "Montenegro",
  "Saint Martin (French part)",
  "Madagascar",
  "Marshall Islands (the)",
  "Republic of North Macedonia",
  "Mali",
  "Myanmar",
  "Mongolia",
  "Macao",
  "Northern Mariana Islands (the)",
  "Martinique",
  "Mauritania",
  "Montserrat",
  "Malta",
  "Mauritius",
  "Maldives",
  "Malawi",
  "Mexico",
  "Malaysia",
  "Mozambique",
  "Namibia",
  "New Caledonia",
  "Niger (the)",
  "Norfolk Island",
  "Nigeria",
  "Nicaragua",
  "Netherlands (the)",
  "Norway",
  "Nepal",
  "Nauru",
  "Niue",
  "New Zealand",
  "Oman",
  "Panama",
  "Peru",
  "French Polynesia",
  "Papua New Guinea",
  "Philippines (the)",
  "Pakistan",
  "Poland",
  "Saint Pierre and Miquelon",
  "Pitcairn",
  "Puerto Rico",
  "Palestine, State of",
  "Portugal",
  "Palau",
  "Paraguay",
  "Qatar",
  "Réunion",
  "Romania",
  "Serbia",
  "Russian Federation (the)",
  "Rwanda",
  "Saudi Arabia",
  "Solomon Islands",
  "Seychelles",
  "Sudan (the)",
  "Sweden",
  "Singapore",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Slovenia",
  "Svalbard and Jan Mayen",
  "Slovakia",
  "Sierra Leone",
  "San Marino",
  "Senegal",
  "Somalia",
  "Suriname",
  "South Sudan",
  "Sao Tome and Principe",
  "El Salvador",
  "Sint Maarten (Dutch part)",
  "Syrian Arab Republic",
  "Eswatini",
  "Turks and Caicos Islands (the)",
  "Chad",
  "French Southern Territories (the)",
  "Togo",
  "Thailand",
  "Tajikistan",
  "Tokelau",
  "Timor-Leste",
  "Turkmenistan",
  "Tunisia",
  "Tonga",
  "Turkey",
  "Trinidad and Tobago",
  "Tuvalu",
  "Taiwan (Province of China)",
  "Tanzania, United Republic of",
  "Ukraine",
  "Uganda",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Holy See (the)",
  "Saint Vincent and the Grenadines",
  "Venezuela (Bolivarian Republic of)",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Viet Nam",
  "Vanuatu",
  "Wallis and Futuna",
  "Samoa",
  "Yemen",
  "Mayotte",
  "South Africa",
  "Zambia",
  "Zimbabwe",
] as const

export type Countries = (typeof COUNTRIES)[number]

export const COUNTRY_ISO_CODE_MAPPING: Record<CountryIsoCodes, Countries> = {
  AD: "Andorra",
  AE: "United Arab Emirates (the)",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei Darussalam",
  BO: "Bolivia (Plurinational State of)",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BS: "Bahamas (the)",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands (the)",
  CD: "Congo (the Democratic Republic of the)",
  CF: "Central African Republic (the)",
  CG: "Congo (the)",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CK: "Cook Islands (the)",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic (the",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands (the) [Malvinas]",
  FM: "Micronesia (Federated States of)",
  FO: "Faroe Islands (the)",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom of Great Britain and Northern Ireland (the)",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia (the)",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory (the)",
  IQ: "Iraq",
  IR: "Iran (Islamic Republic of)",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros (the)",
  KN: "Saint Kitts and Nevis",
  KP: "Korea (the Democratic People's Republic of)",
  KR: "Korea (the Republic of)",
  KW: "Kuwait",
  KY: "Cayman Islands (the)",
  KZ: "Kazakhstan",
  LA: "Lao People's Democratic Republic (the)",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova (the Republic of)",
  ME: "Montenegro",
  MF: "Saint Martin (French part)",
  MG: "Madagascar",
  MH: "Marshall Islands (the)",
  MK: "Republic of North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands (the)",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger (the)",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands (the)",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines (the)",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  PS: "Palestine, State of",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russian Federation (the)",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan (the)",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten (Dutch part)",
  SY: "Syrian Arab Republic",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands (the)",
  TD: "Chad",
  TF: "French Southern Territories (the)",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan (Province of China)",
  TZ: "Tanzania, United Republic of",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands (the)",
  US: "United States of America (the)",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Holy See (the)",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela (Bolivarian Republic of)",
  VG: "Virgin Islands (British)",
  VI: "Virgin Islands (U.S.)",
  VN: "Viet Nam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
}

export const UK_COUNTIES = [
  "Aberdeen City",
  "Aberdeenshire",
  "Angus",
  "Argyll and Bute",
  "Bedfordshire",
  "Belfast",
  "Belfast Greater",
  "Berkshire",
  "Blaenau Gwent",
  "Bridgend",
  "Buckinghamshire",
  "Caerphilly",
  "Cambridgeshire",
  "Cardiff",
  "Carmarthenshire",
  "Ceredigion",
  "Channel Islands",
  "Cheshire",
  "City of Edinburgh",
  "Clackmannanshire",
  "Conwy",
  "Cornwall",
  "County Antrim",
  "County Armagh",
  "County Down",
  "County Fermanagh",
  "County Londonderry",
  "County Tyrone",
  "County of Bristol",
  "Cumbria",
  "Denbighshire",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Dumfries and Galloway",
  "Dunbartonshire",
  "Dundee City",
  "Durham",
  "East Ayrshire",
  "East Dunbartonshire",
  "East Lothian",
  "East Renfrewshire",
  "East Riding of Yorkshire",
  "East Sussex",
  "Essex",
  "Falkirk",
  "Fife",
  "Flintshire",
  "Glasgow City",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Guernsey Channel Islands",
  "Gwynedd",
  "Hampshire",
  "Hereford and Worcester",
  "Herefordshire",
  "Hertfordshire",
  "Highland",
  "Inverclyde",
  "Inverness",
  "Isle of Anglesey",
  "Isle of Barra",
  "Isle of Man",
  "Isle of Wight",
  "Jersey Channel Islands",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "Merseyside",
  "Merthyr Tydfil",
  "Midlothian",
  "Monmouthshire",
  "Moray",
  "Neath Port Talbot",
  "Newport",
  "Norfolk",
  "North Ayrshire",
  "North Lanarkshire",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottinghamshire",
  "Orkney",
  "Orkney Islands",
  "Oxfordshire",
  "Pembrokeshire",
  "Perth and Kinross",
  "Powys",
  "Renfrewshire",
  "Rhondda Cynon Taff",
  "Rutland",
  "Scottish Borders",
  "Shetland Islands",
  "Shropshire",
  "Somerset",
  "South Ayrshire",
  "South Lanarkshire",
  "South Yorkshire",
  "Staffordshire",
  "Stirling",
  "Suffolk",
  "Surrey",
  "Swansea",
  "Torfaen",
  "Tyne and Wear",
  "Vale of Glamorgan",
  "Warwickshire",
  "West Dunbart",
  "West Lothian",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Western Isles",
  "Wiltshire",
  "Worcestershire",
  "Wrexham",
] as const

export type UkCounties = (typeof UK_COUNTIES)[number]

export function getNestedProperty(
  obj: Record<string, any>,
  dotPath: string | string[],
): any {
  if (typeof dotPath === "string") dotPath = dotPath.split(".")

  let value: unknown = obj
  for (let i = 0; i < dotPath.length; i++) {
    value = (value as Record<string, any>)[dotPath[i]]
    if (
      i !== dotPath.length - 1 &&
      (typeof value !== "object" || value === null)
    )
      return
  }

  return value
}

export function withKeyPaths(obj: object, delimiter: string = "."): object {
  function _withKeyPaths(obj: object, path: string[]) {
    return Object.fromEntries(
      Object.entries(obj).map(([key, value]) => {
        const _path = [...path, key]

        if (typeof value === "object" && value !== null)
          value = _withKeyPaths(value as object, _path)

        return [_path.join(delimiter), value]
      }),
    )
  }

  return _withKeyPaths(obj, [])
}

export function getKeyPaths(obj: object, delimiter: string = "."): string[] {
  function _getKeyPaths(obj: object, path: string[]): string[] {
    return Object.entries(obj)
      .map(([key, value]) => {
        const _path = [...path, key]
        const keyPath = _path.join(delimiter)

        return typeof value === "object" && value !== null
          ? [keyPath, ..._getKeyPaths(value as object, _path)]
          : [keyPath]
      })
      .flat()
  }

  return _getKeyPaths(obj, [])
}

export function excludeKeyPaths(
  obj: object,
  exclude: string[],
  delimiter: string = ".",
): any {
  function _excludeKeyPaths(obj: object, path: string[]) {
    return Object.fromEntries(
      Object.entries(obj)
        .map(([key, value]: [string, unknown]) => {
          const _path = [...path, key]

          if (
            typeof value === "object" &&
            value !== null &&
            !(value instanceof Date)
          )
            value = _excludeKeyPaths(value, _path)

          return exclude.includes(_path.join(delimiter)) ? [] : [key, value]
        })
        .filter(entry => entry.length),
    ) as object
  }

  return exclude.length ? _excludeKeyPaths(obj, []) : obj
}

export function generateSecureRandomString(
  length: number,
  charSet: string = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
) {
  // Create an array of 32-bit unsigned integers
  const randomValues = window.crypto.getRandomValues(new Uint8Array(length))

  // Map the random values to characters from our string
  let result = ""
  for (let i = 0; i < length; i++) {
    result += charSet.charAt(randomValues[i] % charSet.length)
  }

  return result
}
